dist: trusty
sudo: false
language: python

git:
  depth: false

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - texlive-fonts-recommended
      - pandoc
      - dvipng
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-science

python:
  - '3.6'

install:
  - travis_retry pip install sphinx sphinx_rtd_theme nbsphinx ipython numpy scipy matplotlib click tqdm setuptools wheel flake8 radon
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then travis_retry pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-linux_x86_64.whl; fi
  - travis_retry pip install torchvision

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then cd docs && mkdir -p _static _templates && PYTHONPATH=../ make html && cd ../; fi
  - python setup.py sdist bdist_wheel

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    verbose: true
    on:
      repo: PIQuIL/QuCumber
      branch: master
  - provider: pypi
    user: PIQuIL
    password:
      secure: ANzomjrVPkzLO7MG9Zekl1Tz/GiO6rJyqZSWlWxF5a8M0+ZBJsFb7Do6kxPNulkEFwEnvjnJpzpY2ryWlhrXnzGZitzWIa5IDLRRHmSQ3GRNPHMIRqf1xle+8/0IwDBuC/eTsOkit7WU1j9lgurCj8snXuTLUVEqf/SecAcLpmLrelRFvz//ZcOopIbwD66RJWT8pYGBH/L3MMIDFj1bIf0UIpXdBXgeTJhxW054+BhdFPGI66IvWU/kOlOcE606wqRqI9bdvop34OewJFnOQ9Elii7LKUPNXoWmq1PrvXCIc1c50BGcLoWFM2CDiOiirzhvvUymtT/Na2BUqPpmnkbi+iRMyaIa6FOa8UIP4TCGuFd4JJlYxaq84bAmikI+1LOOGhfJ0+LACaJaqEM3WRL8VfP/xjWF9GzOuE5W8/fQQUntZaHkqQi4VV2wzULSkc5CpbrR2iX71dROWO4ETzz1wGXmO0dTVfCWMbqk7dT8OPft+tHsWWJqqeCEL3wj1uYEIYpCwLo9oSyVXwrhzRW0dysZfTCx/XfDaws3eFA6iMg6dUoBt12kwGZ5vCbgjBwPOmQrRMUEmYoyZz8n20HKojoxzUpwueFN/nbLv76arJbN8bLeb/GyE6r1Rw0DEzs8f0fBtv5agUnIpMh6EPOFYN4rwHMxt52HU7BB/Kg=
    on:
      repo: PIQuIL/QuCumber
      tags: true

notifications:
  slack:
    secure: GGx0vOR2mg0EofSxv/u7hloC5FKMza7AtyE+Y2wMA506fi+fL9tp4CO2NxhwYjHrvyZu//alLvtrr87GlP2bi62yzfK3JB2Pk1LHFP+EpKclSCmHwURgnwPlb6SfOp45QxFEj+WkJGDkAZOEUkKyqS1/KMj7bg83ca5toXz1npYuCccsYNzM3CuPmM/hOWBuRWzalWo0gQ5nwWC2ptlq62Mjouba89VikTrQ16V6lADDuhod5EUzIdIGTAp4AtKbBUrplMB4wWisVF7UYmTAitsFUAzI+liJMuX9YcsxA/EQHD2m4xvDWQb1uEOONivyNwI7PRwxsp3VSAWqiHuX78i7ABPIstTf78hSzMIpW2VPC9xZuWSz5YJR5VE/yui4VQHQ6ADNm3g5HCrHiAw143rHjkSYFTg9tW0RRcZOXhPIJtdnfY8xMeANKkFU87AtmpPyVtuuMKDE56ECg7BVE9V1RhvGKIP54lRIT9OCLfQ1zJORkmlqZPd3KwSdalqGlzcabsmN6RKvmssHJlv2iq5rpYtXB3yfjiCyGmF3ofqco2CMEO0ZqM3mJD3FKEvudh2a+ZdRff4FG3CydliW9ReerXpBo4Sm8z42XqrxkVnZ51cDD3x394c+8CROQIczMq/K9RQyTHJUyNyFIKHT0ac4J2COkTgg1MVbePchtvg=
